# docker-compose.yml
version: "3.6"
services:
  ojs:
    image: teic/docker-pkp-ojs
    ports: 
      - 8181:80
    environment: 
      - PKP_DATABASE_DRIVER=mysqli
      - PKP_DATABASE_HOST=ojsdb
      - PKP_DATABASE_USERNAME=ojs
      - PKP_DATABASE_PASSWORD=ojs
      - PKP_DATABASE_NAME=ojs
    restart: unless-stopped
  ojsdb:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=ojs
      - MYSQL_USER=ojs
      - MYSQL_PASSWORD=ojs
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: unless-stopped

volumes: 
  db_data:
