name: Docker build and publish

on:
  workflow_dispatch:
  push:
    branches:
       - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - IMAGE_TAG: |
                3.5
                3.5.0
                latest
            BINARY: https://pkp.sfu.ca/ojs/download/ojs-3.5.0-0.tar.gz
          - IMAGE_TAG: |
                3.4
                3.4.0
            BINARY: https://pkp.sfu.ca/ojs/download/ojs-3.4.0-9.tar.gz
          - IMAGE_TAG: |
                3.3
                3.3.0
                lts
            BINARY: https://pkp.sfu.ca/ojs/download/ojs-3.3.0-21.tar.gz
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: TEITechnicalCouncil
          password: ${{ secrets.TEITECHNICALCOUNCIL_PACKAGES_TOKEN }}
      
      # Login against DockerHub registry except on PR
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PETERS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.PETERS_DOCKERHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/teic/docker-pkp-ojs
            teic/docker-pkp-ojs
          tags: ${{ matrix.IMAGE_TAG }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
         context: .
         build-args: |
           BINARY=${{ matrix.BINARY }}
         push: ${{ github.event_name != 'pull_request' }}
         platforms: |
            linux/amd64
            linux/arm64/v8
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}
